import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Link href='/courses'>
              <a>Courses </a>
          </Link>
          <Link href='/users'>
              <a> Users</a>
          </Link>
          <Link href='/posts'>
              <a> Posts</a>
          </Link>
         <Link href='/albums'>
              <a> Albums</a>
          </Link>
      </main>
    </div>
  )
}
